
theme = "catppuccin_frappe"

######## EDITOR ########
[editor]  
color-modes=true
cursorline=true 
cursorcolumn=true
bufferline="always"
end-of-line-diagnostics = "hint"
continue-comments = false
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
left = ["separator", "spacer", "mode", "spacer", "separator", "file-base-name", "separator", "spacer", "spinner"] 
center= ["diagnostics","separator","spacer","position","separator", "spacer"]
right= ["file-modification-indicator"]
mode.normal = "NORMAL"
mode.insert = "EDITING"
mode.select = "SELECT"

[editor.cursor-shape]
insert="underline"
select="hidden"

[editor.gutters.line-numbers]
min-width=1

[editor.auto-save]
focus-lost=true
after-delay.enable=true
after-delay.timeout=6000
######## KEY MAPPING ########

[keys.normal]
# Unselect the line above
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
# Bind `gw` function to enter key
"ret" = "goto_word"

# Yazi integration
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]


[keys.select]
# Unselect the line above
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

